language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install pytest pytest-cov codecov

script:
  - python -m pytest  --cov=./ --capture=sys tests/ --verbose

after_success:
  - codecov
