language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install -r tests/requirements.txt
#  - python setup.py install

script:
  - python -m pytest  --cov=./ --capture=sys tests/ --verbose

after_success:
  - codecov
